### ISSUE TITLE
crong

### ISSUE THREAD

**Issue by maximumpower55** [Septonious/Prismarine-Rewrite#1]
:crong:

**Comment by maximumpower55** [comment]
:trollface:

**Comment by maximumpower55** [comment]
420

**Comment by maximumpower55** [comment]
i know you can see this

**Comment by Polarite** [comment]
least childish iris developer

**Comment by IMS212** [comment]
yes

**Comment by maximumpower55** [comment]
> 

?????? What is going on

**Comment by Polarite** [comment]
frong

**Comment by maximumpower55** [comment]
> frong

Are you in iriscord?

**Comment by Polarite** [comment]
I am!

**Comment by maximumpower55** [comment]
> I am!

What is your discord username

**Comment by Polarite** [comment]
I'm Mr polarite :p, please don't ban me Mr modman.

**Comment by maximumpower55** [comment]
> I'm Mr polarite :p, please don't ban me Mr modman.

Im not a mod just a support team member

**Comment by Polarite** [comment]
welp, why would you ask tho...

**Comment by maximumpower55** [comment]
> welp, why would you ask tho...

I was just confused
