### ISSUE TITLE
crong

### ISSUE THREAD

**Issue by maximumpower55** [Septonious/Prismarine-Rewrite#4]

**Comment by Lolothepro** [comment]
![image](https://user-images.githubusercontent.com/68275908/147785526-1fe0640a-ed83-4a9c-9751-72f4ec83ba16.png)

**Comment by Septonious** [comment]
no

**Comment by maximumpower55** [comment]
:trollface:

**Comment by Lolothepro** [comment]
![](https://github.githubassets.com/images/icons/emoji/trollface.png)
